services:
  - type: web
    name: aeropredict
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt && python generar_datos.py && python training.py"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        fromDatabase:
          name: aeropredict-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: aeropredict-db
    databaseName: predictor_vuelos
    user: vuelos_user
    plan: free
    region: oregon
