name: Ejecutar Flask - Predicción de precios de vuelos

on:
  push:
    branches: [ main ]   # Ejecuta el workflow al hacer push en la rama main
  pull_request:
    branches: [ main ]   # También cuando se crea un pull request hacia main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar aplicación Flask
        env:
          FLASK_APP: app.py
          FLASK_ENV: production
        run: |
          python app.py

      - name: Commit y Push de cambios (si aplica)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Ejecutar Flask app y actualizar datos
          commit_user_name: Aldo Holgado [GitHub Actions]
          commit_user_email: aldoholgado26@gmail.com
          commit_author: aldoholgado
